services:
  web:
    build: .  
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - 8080:8080
  db:
    image: matjpdh/lldb:1.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
